hydra:
    job:
        chdir: False

model: "PlanTL-GOB-ES/roberta-base-biomedical-clinical-es"
symptemist_bigbio_path: "../biomedical/bigbio/hub/hub_repos/symptemist/symptemist.py"
k-fold: False

arguments:
    per_device_train_batch_size: 32
    per_device_eval_batch_size: 32
    fp16: True

    save_strategy: epoch
    output_dir: "/home/Ignacio.Rodriguez/symptemist_biocreative_2023/checkpoints"
    overwrite_output_dir: True
    evaluation_strategy: epoch
    save_total_limit: 2
    num_train_epochs: 10

    load_best_model_at_end: True
    metric_for_best_model: eval_overall_f1

    lr_scheduler_type: linear
    learning_rate: 0.00005
    warmup_ratio: 0.0
    label_smoothing_factor: 0.0
    weight_decay: 0.0
